config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    get '/' => 'homes#top', as: 'top'
    resources :orders, only: [:show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end


  scope module: :public do
    root to: 'homes#top'
    get 'homes/top' => 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    post 'cart_items/create' => 'cart_items#create'
    resources :cart_items, only: [:index, :update, :destroy]

    resources :items, only: [:index, :show]
    get  "orders/confirm" => redirect("orders/new")
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :create, :index, :show]
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resource :customers, only: [:edit, :update, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :orders, through: :orderdetail
  has_one_attached :image
  
  def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg',content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def tax_price
    (self.price * 1.1).round
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.new
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.all
      render :index
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5>商品編集</h5>
      <div class="row">
        <div class="col-md-6 mx-auto mt-5">
          <%= form_with model: @item, url: admin_item_path do |f| %>
            <div class="field">
              <%= f.label :image, "商品画像" %>
              <%= f.file_field :image %>
            </div>
            <div class="field">
              <%= f.label :name, "商品名" %>
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <%= f.label :introduction, "商品説明" %>
              <%= f.text_area :introduction %>
            </div>
            <div class="field">
              <%= f.label :price, "税抜価格" %>
              <%= f.text_field :price %>円
            </div>
            <%= f.submit '変更を保存', class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5>商品一覧</h5>
      <%= link_to new_admin_item_path do %>
        <i class="fa-solid fa-circle-plus"></i>
      <% end %>
      <table class="table">
        <tdead class="table-secondary">
          <tr>
            <th>商品ID</th>
            <th colspan="3">商品名</th>
            <th colspan="3">税抜価格</th>
          </tr>
        </tdead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td>
              <%= item.id %>
            </td>
            <td colspan="3">
              <%= link_to admin_item_path(item.id) do %>
                <%= item.name %>
              <% end %>
            </td>
            <td colspan="3"><%= item.price %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= paginate @items%>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5>商品新規登録</h5>
      <div class="row">
        <div class="col-md-6 mx-auto mt-5">
          <%= form_with model: @item, url: admin_items_path do |f| %>
            <div class="field">
              <%= f.label :image, "商品画像" %>
              <%= f.file_field :image %>
            </div>
            <div class="field">
              <%= f.label :name, "商品名" %>
              <%= f.text_field :name, placeholder: "商品名" %>
            </div>
            <div class="field">
              <%= f.label :introduction, "商品説明" %>
              <%= f.text_area :introduction, placeholder: "ここに説明文を記述します" %>
            </div>
            <div class="field">
              <%= f.label :price, "税抜価格" %>
              <%= f.text_field :price, placeholder: "1000" %>円
            </div>
            <%= f.submit '新規登録',class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <h4>商品詳細</h4>
        <%= image_tag @item.get_item_image(100,100) %>
        <h6>商品名</h6>
        <%= @item.name %></br>
        <h6>商品説明</h6>
        <%= @item.introduction %></br>
        <h6>税込価格(税抜価格)</h6>
        <%= @item.price %></br>
      <%= link_to "編集する", edit_admin_item_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>