config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    get '/' => 'homes#top', as: 'top'
    resources :orders, only: [:show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end


  scope module: :public do
    root to: 'homes#top'
    get 'homes/top' => 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    post 'cart_items/create' => 'cart_items#create'
    resources :cart_items, only: [:index, :update, :destroy]

    resources :items, only: [:index, :show]
    get  "orders/confirm" => redirect("orders/new")
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :create, :index, :show]
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resource :customers, only: [:edit, :update, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  has_many :cart_items, dependent: :destroy
  has_many :orders
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を変更しました。"
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset_sm-1">
      <h5><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h5>
      <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>
        <div class="row">
          <div class="col-3 offset-md-1"><%= f.label "会員ID" %></div>
          <div class="col-3"><%= @customer.id %></div>
        </div>
        <div class="row">
          <div class="col-2 offset-md-1"><%= f.label "氏名" %></div>
          <div class="col-1"></div>
          <div class="col-2"><%= f.text_field :last_name, :size => "15", placeholder: "山田" %></div>
          <div class="col-1"></div>
          <div class="col-3"><%= f.text_field :first_name, :size => "15", placeholder: "花子" %></div>
        </div>
        <div class="row">
          <div class="col-2 offset-md-1"><%= f.label "フリガナ" %></div>
          <div class="col-1"></div>
          <div class="col-2"><%= f.text_field :first_name_kana, :size => "15", placeholder: "ヤマダ" %></div>
          <div class="col-1"></div>
          <div class="col-3"><%= f.text_field :last_name_kana, :size => "15", placeholder: "ハナコ" %></div>
        </div>
        <div class="row">
          <div class="col-2 offset-md-1"><%= f.label "郵便番号" %></div>
          <div class="col-1"></div>
          <div class="col-2"><%= f.text_field :postal_code, :size => "15", placeholder: "×××-×××××" %></div>
        </div>
        <div class="row">
          <div class="col-2 offset-md-1"><%= f.label "住所" %></div>
          <div class="col-1"></div>
          <div class="col-2"><%= f.text_field :address, :size => "40", placeholder: "長野県〇〇市〇〇１−１" %></div>
        </div>
        <div class="row">
          <div class="col-2 offset-md-1"><%= f.label "電話番号" %></div>
          <div class="col-1"></div>
          <div class="col-2"><%= f.text_field :telephone_number, :size => "15", placeholder: "090-1234-5678" %></div>
        </div>
        <div class="row">
          <div class="col-3 offset-md-1"><%= f.label "メールアドレス" %></div>
          <div class="col-2"><%= f.text_field :email, :size => "15", placeholder: "customer@example.com" %></div>
        </div>
        <div class="row">
          <div class="col-3 offset-md-1"><%= f.label "会員ステータス" %></div>
            <div class="col-3">
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効" %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted, "退会" %>
            </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.submit "変更を保存", class: 'btn btn-success' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4>会員一覧</h4>
      <table class="table">
        <tdead>
          <tr>
            <th scope="col">会員ID</th>
            <th scope="col">氏名</th>
            <th scope="col">メールアドレス</th>
          </tr>
          </table>
        </tdead>
      <% @customers.each do |customer| %>
        <table class="table">
          <tbody>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer.id) do %>
                  <%= customer.first_name + customer.last_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
             </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @customers%>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5><%= @customer.last_name + @customer.first_name %>さんの会員詳細画面</h5>
      <div class="row">
        <div class="col-3 offset-md-1"><h6>会員ID</h6></div>
        <div class="col-3"><%= @customer.id %></div>
      </div>
      <div class="row">
        <div class="col-3 offset-md-1"><h6>氏名</h6></div>
        <div class="col-3"><%= @customer.last_name + ' ' + @customer.first_name %></div>
      </div>
      <div class="row">
        <div class="col-3 offset-md-1"><h6>フリガナ</h6></div>
        <div class="col-3"><%= @customer.last_name_kana + ' ' + @customer.first_name_kana %></div>
      </div>
      <div class="row">
        <div class="col-3 offset-md-1"><h6>郵便番号</h6></div>
        <div class="col-3"><%= @customer.postal_code %></div>
      </div>
      <div class="row">
        <div class="col-3 offset-md-1"><h6>住所</h6></div>
        <div class="col-3"><%= @customer.address %></div>
      </div>
      <div class="row">
        <div class="col-3 offset-md-1"><h6>電話番号</h6></div>
        <div class="col-3"><%= @customer.telephone_number %></div>
      </div>
      <div class="row">
        <div class="col-3 offset-md-1"><h6>メールアドレス</h6></div>
        <div class="col-3"><%= @customer.email %></div>
      </div>
      <div class="row">
        <div class="col-3 offset-md-1"><h6>会員ステータス</h6></div>
        <% if @customer.is_deleted == false %>
          <h6 class="text-success">有効</h6>
        <% else %>
          <h6 class="text-secondary">退会</h6>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to "編集する", edit_admin_customer_path, class: 'btn btn-success' %>
      <%= link_to "注文一覧を見る", admin_top_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>