config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    get '/' => 'homes#top', as: 'top'
    resources :orders, only: [:show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end


  scope module: :public do
    root to: 'homes#top'
    get 'homes/top' => 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    post 'cart_items/create' => 'cart_items#create'
    resources :cart_items, only: [:index, :update, :destroy]

    resources :items, only: [:index, :show]
    get  "orders/confirm" => redirect("orders/new")
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :create, :index, :show]
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resource :customers, only: [:edit, :update, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment: { credit_card: 0, transfer: 1 }


  belongs_to :customer
  has_many :orderdetails
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @total = 0
  end

  private

  def order_params
    params.require(:order).permit(:payment, :carriage, :total_amount, :post_code, :address, :home_address)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
    <h6>注文履歴詳細</h6>
    </div>
  </div>
  <%= form_with model: @order, url: admin_order_path, local: true do |f| %>
  <div class="row">
    <div class="col-md-8">
      <h6>購入者</h6>
      <%= link_to admin_customer_path(@customer.id) do %>
        <%= @order.customer.last_name + @order.customer.first_name %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h6>注文日</h6>
      <%= @order.created_at.strftime("%Y-%m-%d") %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h6>配送先</h6>
      <%= @order.post_code %>
      <%= @order.address %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h6>支払方法</h6>
      <%= @order.payment_i18n %>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <table class="table table-borderless">
        <tr>
          <th class="table-secondary">商品名</th>
          <th class="table-secondary">単価(税込)</th>
          <th class="table-secondary">数量</th>
          <th class="table-secondary">小計</th>
        </tr>
        <% @order.orderdetails.each do |orderdetail| %>
        <tr>
          <td><%= orderdetail.item.name %></td>
          <td><%= orderdetail.tax_price %></td>
          <td><%= orderdetail.quantity %></td>
          <td>
            <%= orderdetail.quantity * orderdetail.tax_price %>
          </td>
        </tr>
        <% @total += orderdetail.subtotal %>
        <% end %>
      </table>
    </div>
    <div class="col-md-4">
      <h6>商品合計</h6>
      <%= @total %>
      <h6>送料</h6>
      <%= @order.carriage = 800 %>
      <h6>請求金額合計</h6>
      <% @total += @order.carriage %>
      <%= @total %>
    </div>
  </div>
</div>